# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('surname', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('age', models.IntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('height', models.CharField(max_length=255, verbose_name='\u0420\u043e\u0441\u0442')),
                ('weight', models.CharField(max_length=255, verbose_name='\u0412\u0435\u0441')),
                ('identify', models.CharField(max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('phone_number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('link', models.CharField(max_length=255, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, verbose_name='\u041f\u043e\u043b')),
                ('language', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian'), ('Kyrgyz', 'Kyrgyz')], max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u044f\u0437\u044b\u043a\u043e\u0432')),
                ('ready_to_go', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u0432\u044b\u0435\u0437\u0434\u0443')),
                ('ready_to_mass', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u043c\u0430\u0441\u0441\u043e\u0432\u044b\u043c \u0440\u043e\u043b\u044f\u043c')),
                ('image', models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430')),
                ('status', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0430\u043a\u0442\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ActorsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0430\u043a\u0442\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
            },
        ),
    ]
