# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('surname', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('age', models.IntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('height', models.CharField(max_length=255, verbose_name='\u0420\u043e\u0441\u0442')),
                ('weight', models.CharField(max_length=255, verbose_name='\u0412\u0435\u0441')),
                ('identify', models.CharField(max_length=255, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('phone_number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('body', models.CharField(choices=[('small', '\u043c\u0430\u043b\u0435\u043d\u044c\u043a\u043e\u0435'), ('normal', '\u0441\u0440\u0435\u0434\u043d\u0435\u0435'), ('big', '\u0431\u043e\u043b\u044c\u0448\u043e\u0435')], max_length=255, verbose_name='\u0422\u0435\u043b\u043e\u0441\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('type_of_actor', models.CharField(max_length=255)),
                ('staj', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, verbose_name='\u041e\u043f\u044b\u0442 \u0441\u044a\u0435\u043c\u043e\u043a')),
                ('category', models.CharField(max_length=255, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('color', models.CharField(max_length=255, verbose_name='\u0426\u0432\u0435\u0442 \u0412\u043e\u043b\u043e\u0441')),
                ('talent', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0432\u044b\u043a\u0438')),
                ('link', models.CharField(max_length=255, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, verbose_name='\u041f\u043e\u043b')),
                ('town', models.CharField(choices=[('Bishkek', '\u0411\u0438\u0448\u043a\u0435\u043a'), ('Osh', '\u041e\u0448'), ('Karakol', '\u041a\u0430\u0440\u0430\u043a\u043e\u043b'), ('Djalal-Abad', '\u0414\u0436\u0430\u043b\u0430\u043b \u0410\u0431\u0430\u0434'), ('Cholpon-Ata', '\u0427\u043e\u043b\u043f\u043e\u043d-\u0410\u0442\u0430'), ('Talas', '\u0422\u0430\u043b\u0430\u0441'), ('Batken', '\u0411\u0430\u0442\u043a\u0435\u043d'), ('Karakol', '\u041a\u0430\u0440\u0430\u043a\u043e\u043b'), ('Balykchy', '\u0411\u0430\u043b\u044b\u043a\u0447\u044b')], max_length=255, null=True)),
                ('language', models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u044f\u0437\u044b\u043a\u043e\u0432')),
                ('ready_to_go', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u0432\u044b\u0435\u0437\u0434\u0443')),
                ('ready_to_mass', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u043c\u0430\u0441\u0441\u043e\u0432\u044b\u043c \u0440\u043e\u043b\u044f\u043c')),
                ('image', models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443')),
                ('index_image', models.FileField(upload_to='', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430')),
                ('status', models.CharField(choices=[('VIP', 'VIP'), ('BASIC', 'BASIC')], max_length=255, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('other_talent', models.CharField(max_length=255, verbose_name='\u0414\u0440\u0443\u0433\u0438\u0435 \u041d\u0430\u0432\u044b\u043a\u0438')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0430\u043a\u0442\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ActorsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0410\u043a\u0442\u0435\u0440\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0430\u043a\u0442\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0410\u043a\u0442\u0435\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('region', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('image', models.ImageField(upload_to='', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u041b\u043e\u043a\u0430\u0446\u0438\u0439',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u041b\u043e\u043a\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Location', verbose_name='\u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u041b\u043e\u043a\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u043e\u043a\u0430\u0446\u0438\u0439',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u043e\u043a\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='MovieMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('lastname', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('surname', models.CharField(max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('job_type', models.CharField(max_length=255, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f')),
                ('education', models.CharField(max_length=255, verbose_name='\u041e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('languages', models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u042f\u0437\u044b\u043a\u043e\u0432')),
                ('ready_to_go', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('experience', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043a\u0438\u043d\u0435\u043c\u0430\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0441\u0442\u043e\u0432',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043a\u0438\u043d\u0435\u043c\u0430\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0441\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0441\u0442\u0430')),
                ('description', models.CharField(max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u043e\u0441\u0442\u0430')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0441\u0442\u0430')),
                ('image', models.ImageField(upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('about', models.TextField(verbose_name='\u041e\u0431 \u0410\u0433\u0435\u043d\u0441\u0442\u0432\u0435')),
                ('address', models.CharField(max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('site', models.CharField(max_length=255, verbose_name='\u0421\u0430\u0439\u0442')),
                ('number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('email', models.EmailField(max_length=254, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
                ('image', models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0421\u0442\u0443\u0434\u0438\u0438',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0421\u0442\u0443\u0434\u0438\u0438',
            },
        ),
    ]
