# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0441\u0435\u0441\u0441\u0438\u0438 \u0421\u0442\u0443\u0434\u0438\u0439',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0441\u0435\u0441\u0441\u0438\u0438 \u0421\u0442\u0443\u0434\u0438\u0439',
            },
        ),
        migrations.AddField(
            model_name='moviemaker',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 30, 11, 15, 10, 888056, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviemaker',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 30, 11, 15, 13, 505600, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='apparat',
            field=models.CharField(default=datetime.datetime(2017, 1, 30, 11, 15, 15, 711925, tzinfo=utc), max_length=255, verbose_name='\u0410\u043f\u043f\u0430\u0440\u0430\u0442\u0443\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='square',
            field=models.CharField(default=datetime.datetime(2017, 1, 30, 11, 15, 18, 35221, tzinfo=utc), max_length=255, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0421\u0442\u0443\u0434\u0438\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 30, 11, 15, 20, 230595, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studio',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 30, 11, 15, 22, 289534, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studioimage',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Studio', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0421\u0442\u0443\u0434\u0438\u044e'),
        ),
    ]
