# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170130_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='\u0412\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043b\u0438\u043d\u043a')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Studio', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0421\u0442\u0443\u0434\u0438\u044e')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e\u0441\u0435\u0441\u0441\u0438\u0438 \u0421\u0442\u0443\u0434\u0438\u0439',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e\u0441\u0435\u0441\u0441\u0438\u0438 \u0421\u0442\u0443\u0434\u0438\u0439',
            },
        ),
    ]
