# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170111_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='town',
            field=models.CharField(choices=[('Bishkek', '\u0411\u0438\u0448\u043a\u0435\u043a'), ('Osh', '\u041e\u0448'), ('Karakol', '\u041a\u0430\u0440\u0430\u043a\u043e\u043b'), ('Djalal-Abad', '\u0414\u0436\u0430\u043b\u0430\u043b \u0410\u0431\u0430\u0434'), ('Cholpon-Ata', '\u0427\u043e\u043b\u043f\u043e\u043d-\u0410\u0442\u0430'), ('Talas', '\u0422\u0430\u043b\u0430\u0441'), ('Batken', '\u0411\u0430\u0442\u043a\u0435\u043d'), ('Karakol', '\u041a\u0430\u0440\u0430\u043a\u043e\u043b'), ('Balykchy', '\u0411\u0430\u043b\u044b\u043a\u0447\u044b')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='language',
            field=models.CharField(choices=[('Russian', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('Enlish', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'), ('Deutch', '\u041d\u0435\u043c\u0435\u0446\u043a\u0438\u0439'), ('France', '\u0424\u0440\u0430\u043d\u0446\u0443\u0437\u0441\u043a\u0438\u0439')], max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u044f\u0437\u044b\u043a\u043e\u0432'),
        ),
    ]
