# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_studiolink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiolink',
            options={'verbose_name': 'Video \u0421\u0442\u0443\u0434\u0438\u0439', 'verbose_name_plural': 'Video \u0421\u0442\u0443\u0434\u0438\u0439'},
        ),
    ]
