# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_moviemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='index_image',
            field=models.FileField(default=datetime.datetime(2017, 1, 25, 10, 39, 35, 344781, tzinfo=utc), upload_to='', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.FileField(upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443'),
        ),
    ]
