# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20170207_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0435\u043a\u0442\u0430')),
                ('image', models.ImageField(upload_to='', verbose_name='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0443')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Studio', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 studio')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u041f\u0440\u043e\u0435\u043a\u0442',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u041f\u0440\u043e\u0435\u043a\u0442\u0430',
            },
        ),
    ]
