# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20170125_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviemaker',
            options={'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043a\u0438\u043d\u0435\u043c\u0430\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0441\u0442\u043e\u0432', 'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043a\u0438\u043d\u0435\u043c\u0430\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0441\u0442\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='moviemaker',
            name='image',
            field=models.FileField(default=datetime.datetime(2017, 1, 25, 10, 51, 25, 25227, tzinfo=utc), upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='education',
            field=models.CharField(max_length=255, verbose_name='\u041e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='languages',
            field=models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u042f\u0437\u044b\u043a\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
