# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_projectstudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='Images')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0441 \u0444\u043e\u0440\u043c\u044b',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0441 \u0444\u043e\u0440\u043c\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='projectstudio',
            options={'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u041f\u0440\u043e\u0435\u043a\u0442 Studio', 'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u041f\u0440\u043e\u0435\u043a\u0442\u0430 Studio'},
        ),
        migrations.RenameField(
            model_name='locationimage',
            old_name='news',
            new_name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('Priroda', 'Priroda'), ('Interyer', 'Interyer')], default=datetime.datetime(2017, 2, 14, 11, 32, 45, 716357, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('\u0421\u043e\u0432\u0435\u0442\u044b', '\u0421\u043e\u0432\u0435\u0442\u044b'), ('\u041d\u043e\u0432\u043e\u0441\u0442\u0438', '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'), ('\u041a\u0430\u0441\u0442\u0438\u043d\u0433\u0438', '\u041a\u0430\u0441\u0442\u0438\u043d\u0433\u0438')], default=datetime.datetime(2017, 2, 14, 11, 32, 47, 502656, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='ready_to_go',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u0432\u044b\u0435\u0437\u0434\u0443'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='ready_to_mass',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u043c\u0430\u0441\u0441\u043e\u0432\u044b\u043c \u0440\u043e\u043b\u044f\u043c'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('\u041c\u0443\u0436\u0441\u043a\u043e\u0439', 'Male'), ('\u0416\u0435\u043d\u0441\u043a\u0438\u0439', 'Female')], max_length=255, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='staj',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u041e\u043f\u044b\u0442 \u0441\u044a\u0435\u043c\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='category',
            field=models.CharField(choices=[('\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b', '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b'), ('\u041b\u044e\u0431\u0438\u0442\u0435\u043b\u044c', '\u041b\u044e\u0431\u0438\u0442\u0435\u043b\u044c'), ('\u041d\u043e\u0432\u0438\u0447\u043e\u043a', '\u041d\u043e\u0432\u0438\u0447\u043e\u043a')], max_length=255),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='ready_to_go',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255),
        ),
    ]
