# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20170214_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='body',
        ),
        migrations.AlterField(
            model_name='formfile',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Images'),
        ),
    ]
