# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_moviemaker_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('about', models.TextField(verbose_name='\u041e\u0431 \u0410\u0433\u0435\u043d\u0441\u0442\u0432\u0435')),
                ('address', models.CharField(max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('site', models.CharField(max_length=255, verbose_name='\u0421\u0430\u0439\u0442')),
                ('number', models.CharField(max_length=255, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('email', models.EmailField(max_length=254, verbose_name='\u041f\u043e\u0447\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0421\u0442\u0443\u0434\u0438\u0438',
                'verbose_name_plural': '\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0421\u0442\u0443\u0434\u0438\u0438',
            },
        ),
    ]
