# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20170214_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='body',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='ready_to_go',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='ready_to_mass',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='weight',
        ),
        migrations.AddField(
            model_name='formfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 4, 8, 25, 37, 860421, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 4, 8, 25, 40, 286894, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='other_talent',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0414\u0440\u0443\u0433\u0438\u0435 \u041d\u0430\u0432\u044b\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('\u041c\u0443\u0436\u0441\u043a\u043e\u0439', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), ('\u0416\u0435\u043d\u0441\u043a\u0438\u0439', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], max_length=255, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Images'),
        ),
    ]
