# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20170212_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationimage',
            old_name='news',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='actor',
            name='ready_to_go',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u0432\u044b\u0435\u0437\u0434\u0443'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='ready_to_mass',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u0413\u043e\u0442\u043e\u0432\u043d\u043e\u0441\u0442\u044c \u043a \u043c\u0430\u0441\u0441\u043e\u0432\u044b\u043c \u0440\u043e\u043b\u044f\u043c'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('\u041c\u0443\u0436\u0441\u043a\u043e\u0439', 'Male'), ('\u0416\u0435\u043d\u0441\u043a\u0438\u0439', 'Female')], max_length=255, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='staj',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255, verbose_name='\u041e\u043f\u044b\u0442 \u0441\u044a\u0435\u043c\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='category',
            field=models.CharField(choices=[('\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b', '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b'), ('\u041b\u044e\u0431\u0438\u0442\u0435\u043b\u044c', '\u041b\u044e\u0431\u0438\u0442\u0435\u043b\u044c'), ('\u041d\u043e\u0432\u0438\u0447\u043e\u043a', '\u041d\u043e\u0432\u0438\u0447\u043e\u043a')], max_length=255),
        ),
        migrations.AlterField(
            model_name='moviemaker',
            name='ready_to_go',
            field=models.CharField(choices=[('\u0414\u0430', 'Yes'), ('\u041d\u0435\u0442', 'No')], max_length=255),
        ),
    ]
