# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20170215_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 15, 10, 57, 21, 916699, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 15, 10, 57, 24, 908486, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
