# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.FileField(default=datetime.datetime(2017, 1, 25, 11, 49, 9, 771203, tzinfo=utc), upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
            preserve_default=False,
        ),
    ]
