# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_auto_20170215_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f \u0430\u043a\u0442\u0435\u0440\u0430 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='other_talent',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0414\u0440\u0443\u0433\u0438\u0435 \u041d\u0430\u0432\u044b\u043a\u0438'),
        ),
    ]
