# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_news_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('region', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('image', models.ImageField(upload_to='', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Location', verbose_name='\u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u041b\u043e\u043a\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u043e\u043a\u0430\u0446\u0438\u0439',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043b\u043e\u043a\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='body',
            field=models.CharField(choices=[('small', '\u043c\u0430\u043b\u0435\u043d\u044c\u043a\u043e\u0435'), ('normal', '\u0441\u0440\u0435\u0434\u043d\u0435\u0435'), ('big', '\u0431\u043e\u043b\u044c\u0448\u043e\u0435')], default=datetime.datetime(2017, 1, 27, 14, 57, 42, 485254, tzinfo=utc), max_length=255, verbose_name='\u0422\u0435\u043b\u043e\u0441\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='category',
            field=models.CharField(default=datetime.datetime(2017, 1, 27, 14, 57, 53, 177308, tzinfo=utc), max_length=255, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='color',
            field=models.CharField(default=datetime.datetime(2017, 1, 27, 14, 57, 59, 159939, tzinfo=utc), max_length=255, verbose_name='\u0426\u0432\u0435\u0442 \u0412\u043e\u043b\u043e\u0441'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='other_talent',
            field=models.CharField(default=datetime.datetime(2017, 1, 27, 14, 58, 1, 428105, tzinfo=utc), max_length=255, verbose_name='\u0414\u0440\u0443\u0433\u0438\u0435 \u041d\u0430\u0432\u044b\u043a\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='staj',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=datetime.datetime(2017, 1, 27, 14, 58, 4, 185483, tzinfo=utc), max_length=255, verbose_name='\u041e\u043f\u044b\u0442 \u0441\u044a\u0435\u043c\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='talent',
            field=models.CharField(default=datetime.datetime(2017, 1, 27, 14, 58, 7, 285103, tzinfo=utc), max_length=255, verbose_name='\u041d\u0430\u0432\u044b\u043a\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='type_of_actor',
            field=models.CharField(default=datetime.datetime(2017, 1, 27, 14, 58, 10, 665352, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='language',
            field=models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u043d\u0438\u0435 \u044f\u0437\u044b\u043a\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='link',
            field=models.CharField(max_length=255, verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube'),
        ),
    ]
