# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_auto_20170218_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='ready_to_go',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='ready_to_mass',
        ),
    ]
